// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoContato_API.Data;

namespace ProjetoContato.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ProjetoContato_API.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DataNasc");

                    b.Property<string>("Nome");

                    b.Property<string>("Sobrenome");

                    b.Property<string>("Telefone");

                    b.HasKey("Id");

                    b.ToTable("pessoas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNasc = "01/05/2000",
                            Nome = "Maria",
                            Sobrenome = "José",
                            Telefone = "81784568898"
                        },
                        new
                        {
                            Id = 2,
                            DataNasc = "25/06/1999",
                            Nome = "João",
                            Sobrenome = "Paulo",
                            Telefone = "81445575525"
                        },
                        new
                        {
                            Id = 3,
                            DataNasc = "11/07/1980",
                            Nome = "Lucas",
                            Sobrenome = "Machado",
                            Telefone = "81578962542"
                        },
                        new
                        {
                            Id = 4,
                            DataNasc = "04/02/1999",
                            Nome = "Juca",
                            Sobrenome = "Chaves",
                            Telefone = "81568896647"
                        },
                        new
                        {
                            Id = 5,
                            DataNasc = "22/09/2010",
                            Nome = "Luciano",
                            Sobrenome = "Gomes",
                            Telefone = "81487554878"
                        },
                        new
                        {
                            Id = 6,
                            DataNasc = "29/07/1987",
                            Nome = "Antônio",
                            Sobrenome = "Ferreira",
                            Telefone = "81545666822"
                        },
                        new
                        {
                            Id = 7,
                            DataNasc = "12/05/2010",
                            Nome = "Larissa",
                            Sobrenome = "Cruz",
                            Telefone = "81456387864"
                        },
                        new
                        {
                            Id = 8,
                            DataNasc = "22/10/1982",
                            Nome = "Claudio",
                            Sobrenome = "Fernandes",
                            Telefone = "81478963458"
                        },
                        new
                        {
                            Id = 9,
                            DataNasc = "05/05/2015",
                            Nome = "Emanuel",
                            Sobrenome = "Lima",
                            Telefone = "81489365425"
                        },
                        new
                        {
                            Id = 10,
                            DataNasc = "14/07/2012",
                            Nome = "Lidiane",
                            Sobrenome = "Almeida",
                            Telefone = "81455224568"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
